version: '3'
services:
  jira:
    image: cptactionhank/atlassian-jira-software:7.5.1
    restart: always
    volumes:
      - jira-logs:/opt/atlassian/jira/logs
      - jira-data:/var/atlassian/jira

  confluence:
    image: cptactionhank/atlassian-confluence:6.3.4
    restart: always
    volumes:
      - confluence-logs:/opt/atlassian/confluence/logs
      - confluence-data:/var/atlassian/confluence

  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "445:445"
    links:
      - jira
      - confluence
    volumes:
      - ./:/src
    command: ./src/scripts/run_nginx.sh
    environment:
      - DOMAIN=${FULL_DOMAIN}

volumes:
  jira-data:
  jira-logs:
  confluence-data:
  confluence-logs:
  bitbucket-data:
  database-data:
